workflows:
    native-android:
        name: Native Android
        instance_type: mac_mini
        max_build_duration: 60
        environment:
            node: latest
            xcode: 12.2
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: '*'
                  include: true
                  source: true
        scripts:
            - name: Set up local.properties
              script: |
              echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
            - name: Flutter analyze
              script: |
                flutter analyze
            - name: Flutter Unit test
              script: |
                flutter test
            # - name: Set up keystore
            #   script: |
            #         echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
            #         # The following script creates key.properties file and stores the credentials in it. As we configure code signing in app/build.gradle file, the following part is unnecessary unless code signing is configured differently as explained in the documentation: https://docs.codemagic.io/flutter-code-signing/android-code-signing/
            #         # cat >> "$FCI_BUILD_DIR/key.properties" <<EOF
            #         # storePassword=$CM_KEYSTORE_PASSWORD
            #         # keyPassword=$CM_KEY_ALIAS_PASSWORD
            #         # keyAlias=$CM_KEY_ALIAS_USERNAME
            #         # storeFile=/tmp/keystore.keystore
            #         # EOF
            - name: Build Android APK
              script: |
                flutter build apk --debug
            - name: Build Android test APK
              script: |
                flutter test 
            # - name: Build Android production release
            #   script: |
            #     ./gradlew assembleRelease    
        artifacts:
            - app/build/outputs/**/*.apk
        publishing:
            email:
                recipients:
                    - nikbarch@gmail.com
                notify:
                  success: true
                  failure: false   
            # google_play:                          # For publishing your Android app to Google Play
            #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
            #     track: alpha                      # Name of the track: internal, alpha, beta, production

    web:
        name: Flutter Web
        instance_type: mac_mini
        max_build_duration: 60
        environment:
            node: latest
            xcode: 12.2
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: '*'
                  include: true
                  source: true
        scripts:
            - name: Build Web
              script: |
                flutter config --enable-web
                flutter build web --release
                cd build/web
                7z a -r ../web.zip ./*  